spring.application.name=ecommerce


server.port=8082

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/springbootecommerce
spring.datasource.username=root
spring.datasource.password=root123


#jwt properties
#app.jwtSecret=${JWT_SECRET}
#app.jwtExpiration=${JWT_EXPIRATION}

app.jwtSecret=abakanksbcskjew092uQhklskjfhiuwhibvbkajfhivbfjfheueuehjjdmcmmmmmmmmmmmmsj98182827abakanksbcskjew092uQhklskjfhiuwhibvbkajfhivbfjfheueuehjjdmcmmmmmmmmmmmmsj98182827
app.jwtExpiration=6000000000